"""add maintenance votes table

Revision ID: abb4ae9dbeb9
Revises: 02fed311af6d
Create Date: 2026-02-17 13:24:20.677775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb4ae9dbeb9'
down_revision: Union[str, Sequence[str], None] = '02fed311af6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_votes',
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_request_id', 'user_id')
    )
    op.alter_column('maintenance_requests', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('maintenance_requests', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('priority', sa.VARCHAR(), server_default=sa.text("'MEDIUM'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('maintenance_requests', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('maintenance_votes')
    # ### end Alembic commands ###
