"""drop assigned_to_user_id from maintenance_requests

Revision ID: d0a33c190aec
Revises: abb4ae9dbeb9
Create Date: 2026-02-18 12:28:25.947088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a33c190aec'
down_revision: Union[str, Sequence[str], None] = 'abb4ae9dbeb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('maintenance_requests_assigned_to_user_id_fkey'), 'maintenance_requests', type_='foreignkey')
    op.drop_column('maintenance_requests', 'assigned_to_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('assigned_to_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('maintenance_requests_assigned_to_user_id_fkey'), 'maintenance_requests', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
